### ISSUE TITLE
Cross compiling for Arm

### ISSUE THREAD

**Issue by sreenathr-invenco** [osvenskan/posix_ipc#18]
Please provide some simple instructions for cross compiling posix_ipc whrein:
Compilation host is X86 Linux and
Intended target is Arm 32 bit

**Comment by osvenskan** [comment]
Sorry, but documenting compilation scenarios I have time to support. Python handles the compiling for me. Have you tried things that don't work? Googling for 'gcc cross compile arm' brings up a lot of articles.

**Comment by 51m** [comment]
@sreenathr-invenco I believe you can move the source code folder into your Arm Linux. And assuming you are using python3: 
_sudo python3 setup.py install_
If you have all the dependencies (normally just python3-dev) and the gcc compiler (or gcc toolchain for your emedded linux) installed on your Arm Linux, the library should be installed under your /usr/lib/python3.x/site-packages/

**Comment by osvenskan** [comment]
@sreenathr-invenco Did 51m's comment help? Unless there's an update to report, I'm going to close this ticket.
