### ISSUE TITLE
Problems in the execution of setup.py

### ISSUE THREAD

**Issue by er-n1ck** [osvenskan/posix_ipc#25]
Hi, I'm trying tu use your code on a Windows machine, when I execute the code in Visual Studio he says:
`Traceback (most recent call last):
  File "c:/Users/Lorenzo/Desktop/posix_ipc-master/setup.py", line 13, in <module>
    VERSION = open("VERSION").read().strip()
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION' `.
I dont't know what can I do to fix the problem.

**Comment by osvenskan** [comment]
Hi @er-n1ck , `setup.py` is meant to be executed from a command line, and from the directory as `setup.py`, with the command `python setup.py install`. I don't test it in other execution environments. I definitely don't test Visual Studio, and I expect it's getting in the way here. 

If you run `python setup.py install` from a command line and you get the same error, let me know. 

More importantly, keep in mind that `posix_ipc` requires POSIX support in the operating system, and Windows historically hasn't supported POSIX. I don't know if the new WSL changes that.

**Comment by er-n1ck** [comment]
Thanks for the fast response, I tryed by cmd terminal of Windows and get the same error. 
But you are right, I completely forget to think about POSIX, I was so happy to find something to implement those structures that I turned off my brain. I will try to do the same thing in a virtual machine with a unix like OS and I will let you know if the problem persists.

**Comment by osvenskan** [comment]
@er-n1ck Any updates? If not, I'll close this soon.
