### ISSUE TITLE
Version discrepancy between pypi and github

### ISSUE THREAD

**Issue by risicle** [osvenskan/posix_ipc#27]
Could you please either release 1.0.4 & 1.0.5 on pypi and/or tag pypi's apparent "1.1.0" in this repo? The discrepancy between the two sets off alarm bells in the heads of cautious people over whether the pypi account has been hijacked etc.

**Comment by osvenskan** [comment]
I appreciate your caution. I'm not sure what you mean about the versions, though, can you explain more? 1.0.4 and 1.0.5 are on PyPI --

https://pypi.org/project/posix-ipc/1.0.4/
https://pypi.org/project/posix-ipc/1.0.5/

Both of those releases are tagged on GitHub: https://github.com/osvenskan/posix_ipc/tags

There is no version 1.1.0; 1.0.5 is the latest version: http://semanchuk.com/philip/posix_ipc/

Are you perhaps thinking of the sibling package `sysv_ipc` (http://semanchuk.com/philip/sysv_ipc/) for which I recently released version 1.1.0?

**Comment by risicle** [comment]
:confused: I'm trying to figure out how I ended up on the wrong github repo.

Think I must have blindly clicked the first semanchuk.com link I saw on the pypi readme and just gone down that rabbit hole...

Please ignore...

**Comment by osvenskan** [comment]
no worries!
