### ISSUE TITLE
Convert doc to Markdown

### ISSUE THREAD

**Issue by osvenskan** [osvenskan/posix_ipc#29]
## Summary

Currently my personal site is the primary repository for the documentation. Since it's formatted in HTML, it's less easy to read on GitHub than it could be. If the doc was in Markdown, it's be easier to change the project's organization to have GitHub be the primary source of both the doc and source code.

**Comment by christopolise** [comment]
I'd be willing to look into this if help is still wanted!

**Comment by osvenskan** [comment]
Hi @christopolise, thanks for the offer! I created a new branch for this work. I integrated the work from @GreatBahram from #31 and now I'd like to build on that. There are two tasks you could take on. One is to convert the usage instructions in ReadMe.html into markdown in `usage.md`. Another is to convert `history.html` to markdown. Any progress on these would be appreciated.

https://github.com/osvenskan/posix_ipc/tree/29-convert-doc-to-markdown

**Comment by christopolise** [comment]
Will do! I am assuming I should just fork the repo and then make a PR when I've made the changes?

**Comment by osvenskan** [comment]
Yep, that works for me, as long as I can merge to https://github.com/osvenskan/posix_ipc/tree/29-convert-doc-to-markdown. Thanks!

**Comment by christopolise** [comment]
Finished these edits and open up a PR #33 . Let me know if there is anything else that needs to be done!

**Comment by osvenskan** [comment]
resolved with the release of 1.1.0
