### ISSUE TITLE
Semaphore class gives "Invalid Parameter" error on Ubuntu

### ISSUE THREAD

**Issue by SZTankWang** [osvenskan/posix_ipc#32]
HI:
I'm trying to use the Semaphore class like this: 
```
sem = posix_ipc.Semaphore(name= <some string>, flags=posix_ipc.O_CREAT, initial_value=1)
```
However, it keeps telling me 
```
ValueError: Invalid parameter(s)
```
I looked at the examples given on this repo, but really cannot identify the problem. 
I would really appreciate your opionins. Thank you!

**Comment by osvenskan** [comment]
You're using it correctly. That works for me --

```python
>>> import posix_ipc
>>> sem = posix_ipc.Semaphore(name='foo', flags=posix_ipc.O_CREAT, initial_value=1)
>>> sem.release()
>>>
```

In your case I suspect a system configuration issue or perhaps a permissions problem. 

You can build your own version of `posix_ipc` with debugging output enabled which may help you find the problem. Build `posix_ipc` with `python setup.py build`, then look in `probe_results.h` for instructions on how to enable debugging output. Edit that file and  then run `python setup.py install`. 

Hope this helps.

**Comment by osvenskan** [comment]
@SZTankWang Do you have any updates on this issue? If not, I'm going to close it.

**Comment by SZTankWang** [comment]
Hi @osvenskan, thank you for your help. Yes, you can close this issue.
