### ISSUE TITLE
Import Error, undefined symbol: shm_unlink

### ISSUE THREAD

**Issue by Chris-Tang6** [osvenskan/posix_ipc#44]
I cloned a project from github and installed it on Ubuntu, but it cant' run. And it arises a ERROR as below which is related to posix_ipc.

```
File "/homeb/tangwuguo/projects/raptorX/DL4DistancePrediction4/DataProcessor.py", line 11, in <module>
    from shared_ndarray import SharedNDArray
  File "build/bdist.linux-x86_64/egg/shared_ndarray/__init__.py", line 3, in <module>
    
ImportError: /homeb/tangwuguo/miniconda3/envs/raptorX/lib/python2.7/site-packages/posix_ipc.so: undefined symbol: shm_unlink
```

**Comment by osvenskan** [comment]
> `/homeb/tangwuguo/miniconda3/envs/raptorX/lib/python2.7`

`                                                ^^^^^^^^^ `

`posix_ipc` dropped support for Python 2.7 a while ago. You can install an older version if you need Python 2.7 support, as documented in the README: https://github.com/osvenskan/posix_ipc/blob/master/README.md#python-27-support

**Comment by Chris-Tang6** [comment]
> 

![image](https://user-images.githubusercontent.com/53926670/216617910-ffe87906-e1e8-482d-b218-9593f06954c6.png)


> > `/homeb/tangwuguo/miniconda3/envs/raptorX/lib/python2.7`
> 
> ` ^^^^^^^^^`
> 
> `posix_ipc` dropped support for Python 2.7 a while ago. You can install an older version if you need Python 2.7 support, as documented in the README: https://github.com/osvenskan/posix_ipc/blob/master/README.md#python-27-support

**Comment by Chris-Tang6** [comment]
I checked the pkg vesion is 1.0.4. It should be suitable to run on python2.7.
![image](https://user-images.githubusercontent.com/53926670/216618260-76beb6fe-9ee7-4d71-9187-4dbd59bf90b8.png)

**Comment by Chris-Tang6** [comment]
I just updated posix-ipc from 1.0.4 to 1.0.5, and the issue was solved. Now I can import this pkg on py2.7
Thank U🙌😉
