### ISSUE TITLE
`Semaphore::release` / `::acquire`  segfault on Linux

### ISSUE THREAD

**Issue by brandenburg** [osvenskan/posix_ipc#51]
The library causes a bus error when calling `acquire` or `release` on a semaphore. Message queues work fine on the same machine. 

On a Raspberry Pi 4 w/ Ubuntu: 

```
$ pip show posix_ipc
Name: posix-ipc
Version: 1.1.1
Summary: POSIX IPC primitives (semaphores, shared memory and message queues) for Python
Home-page: https://github.com/osvenskan/posix_ipc
Author: Philip Semanchuk
Author-email: philip@semanchuk.com
License: http://creativecommons.org/licenses/BSD/
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: 

$ touch /dev/shm/sem.foobar
$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import posix_ipc
>>> sem = posix_ipc.Semaphore('/foobar')
>>> sem.release()
Bus error (core dumped)
```

Same version of the library on an x86 machine w/ Debian, with a more recent Python version from Homebrew:

```
$ touch /dev/shm/sem.foobar
$ python3         
Python 3.11.5 (main, Aug 24 2023, 12:23:19) [GCC 13.1.0] on linux     
Type "help", "copyright", "credits" or "license" for more information.
>>> import posix_ipc                                                  
>>> sem = posix_ipc.Semaphore('/foobar')                              
>>> sem.release()                                                     
Bus error
```

**Comment by osvenskan** [comment]
hi @brandenburg , I don't use Linux, so I can't speak with authority, but I suspect that what you are trying to do is not supported by the operating system. Can you point me to some Linux documentation that says that creating an empty file in `/dev/shm` is the same as calling `sem_open()`?

**Comment by brandenburg** [comment]
Thanks for looking into it. Here's what the [man page](https://man7.org/linux/man-pages/man7/sem_overview.7.html) says: 

>  Accessing named semaphores via the filesystem
       On Linux, named semaphores are created in a virtual filesystem,
       normally mounted under `/dev/shm`, with names of the form
       `sem.somename`.

It's possible to delete leftover semaphores with `rm`, and creation with `touch` works fine for POSIX message queues ([man page](https://man7.org/linux/man-pages/man7/mq_overview.7.html), see section on `/dev/mqueue`), so extrapolated that it would work for semaphores, too. I'll double-check if that's the root cause.

Note that the `posix_ipcs.Semaphore` constructor does not return an error, so I had assumed that opening of the existing semaphore worked ok.

**Comment by brandenburg** [comment]
You are right. This works ok:

```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import posix_ipc
>>> sem = posix_ipc.Semaphore('/new-sem', flags=posix_ipc.O_CREAT)
>>> sem.release()
```

Afterwards, this also:
```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux    
Type "help", "copyright", "credits" or "license" for more information.
>>> import posix_ipc                                                  
>>> sem = posix_ipc.Semaphore('/new-sem')                             
>>> sem.acquire()
```

Sorry for the noise. 

I'm just surprised I was able to open the semaphore at all when it wasn't created properly. Going by the man pages for [`sem_wait`](https://man7.org/linux/man-pages/man3/sem_wait.3.html) and [`sem_post`](https://man7.org/linux/man-pages/man3/sem_post.3.html), I would have expected an exception wrapping `EINVAL`, not a crash of the process. 

> `EINVAL` `sem` is not a valid semaphore.

**Comment by brandenburg** [comment]
Ah, I think here's what's going on. Linux implements `sem_open` entirely in userspace. Let's run the following example under `strace`.

```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import posix_ipc
>>> sem = posix_ipc.Semaphore('/new-sem')
```

We observe the following system-call sequence:

```
...
openat(AT_FDCWD, "/dev/shm/sem.new-sem", O_RDWR|O_NOFOLLOW) = 3               
newfstatat(3, "", {st_mode=S_IFREG|0600, st_size=32, ...}, AT_EMPTY_PATH) = 0 
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0xffff8f286000       
...
```

So the library literally just maps the file in `/dev/shm`. Note the mapping has a size of 32 bytes. 

Let's create a "semaphore" file manually via touch:

```
touch /dev/shm/sem.causes-a-problem
```

This is of course a zero-length file now, whereas the library-created file has a size of 32 bytes:

```
$ ls -lh
total 4.0K
-rw-rw-r-- 1 bbb bbb  0 Sep 23 16:03 sem.causes-a-problem
-rw------- 1 bbb bbb 32 Sep 23 15:35 sem.new-sem
```

So let's try opening that "semaphore":

```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import posix_ipc
>>> sem = posix_ipc.Semaphore('/causes-a-problem')
>>> sem.release()
Bus error (core dumped)
```

It crashes, as before. In the `strace` log we can find this:

```
openat(AT_FDCWD, "/dev/shm/sem.causes-a-problem", O_RDWR|O_NOFOLLOW) = 3    
newfstatat(3, "", {st_mode=S_IFREG|0664, st_size=0, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0xffffa02f3000     
```

So the library implementation of `sem_open` dutifully mapped the zero-length file without complaint. Then when it tries to increase the semaphore count, it crashes because nothing is actually mapped there… 🤷‍♂️

**Comment by osvenskan** [comment]
> creation with `touch` works fine for POSIX message queues 

I believe you if it works for you, but I don't see that definitively stated in the `man` page. It says --

> the message queues on the system can be viewed and manipulated using the commands usually used for files (e.g., ls(1) and rm(1)).

A lawyer might argue that "manipulated" includes "created" but my guess is that the author didn't intend that, and would have included `touch` alongside of `ls` and `rm` if that was a viable option. In addition, the next section says --

> The contents of each file in the directory consist of a single line containing information about the queue:
>     `$ cat /dev/mqueue/mymq`
>     `QSIZE:129     NOTIFY:2    SIGNO:0    NOTIFY_PID:8260`

Knowing this, I would be surprised if using `touch /dev/mqueue/mymq` to create a message didn't also cause a segfault or some similar bad outcome. Creating an empty file where the kernel expects a file that contains key data is playing with fire, just as with the semaphore.

**Comment by brandenburg** [comment]
That's a reasonable guess, but I suspect `/dev/mqueue` works differently. `/dev/mqueue` is a virtual file system backed by the `mqueue` driver, which doesn't serve any other purpose but to expose POSIX message queues. So if the intention was to disallow creation of message queues via FS operations, it would simply not be possible, since `inode` creation is "opt-in" (the FS driver needs to explicitly implement it).

To be sure, let's have a look at the kernel. 

The relevant Linux kernel code can be found here: https://elixir.bootlin.com/linux/v6.5.5/source/ipc/mqueue.c

Here's the `read` implementation that produces the "QSIZE..." status line: https://elixir.bootlin.com/linux/v6.5.5/source/ipc/mqueue.c#L635 
It's not the contents of a regular file, just meta-data of the kernel-space message queue object [serialized with `snprintf`](https://elixir.bootlin.com/linux/v6.5.5/source/ipc/mqueue.c#L643).

The mqueue `inode` operations are assembled here: https://elixir.bootlin.com/linux/v6.5.5/source/ipc/mqueue.c#L1657

The creation method is [`mqueue_create`](https://elixir.bootlin.com/linux/v6.5.5/source/ipc/mqueue.c#L611), which just calls [`mqueue_create_attr`](https://elixir.bootlin.com/linux/v6.5.5/source/ipc/mqueue.c#L566). After some error checking, it calls [`mqueue_get_inode`](https://elixir.bootlin.com/linux/v6.5.5/source/ipc/mqueue.c#L290), which really does allocate and [initialize](https://elixir.bootlin.com/linux/v6.5.5/source/ipc/mqueue.c#L313) a message queue object. 

So in addition to the observation that creation via `touch` works just fine in my testing, the relevant kernel code indicates that POSIX message queue creation via the file system interface is expected and supported. 

The trouble in the semaphore case arises because `/dev/shm` is really just a `tmpfs` mount, which is not a special-purpose FS. Rather, `tmpfs` is  designed to be a regular file system backed (only) by memory. The fact that POSIX semaphores are backed by memory-mapped 32-byte files in `/dev/shm` is only a `libc` convention. To the kernel, these are not special files, and it's possible to store any other regular files in `/dev/shm` (which is not possible in `/dev/mqueue`).  The inter-process synchronization is achieved with FUTEX operations, which work on any (shared) memory. On a `tempfs`, `touch` really does create just an empty file. 

So while Linux's POSIX message queue and semaphore interfaces looked more or less similar to me based on a quick skim of the man pages, after a more careful inspection, these are technically actually two completely different APIs. Observations about one don't generalize to the other. Oops. 

From a user's POV, I would argue that `sem_open` should (loudly) fail if there's a file of the wrong size (or wrong memory layout) in the way, instead of (silently) preparing the process to crash when the process subsequently tries to actually increment or decrement the semaphore's counter. While a segfault may be the usual and expected result when (accidentally) straying from supported behavior when doing C development, I expect Python to never segfault due to user error (which is why it initially didn't even occur to me to dig deeper before filing this issue). 

However, this is clearly not a `posix_ipc` issue, but something the underlying `libc` should handle better, so I'll close this misdirected issue. Thank you for looking into it right away; I'm sorry I wasted your time.

Maybe this gotcha is worth a note in the  [platform notes](https://github.com/osvenskan/posix_ipc/blob/develop/USAGE.md#platform-notes) in `USAGE.md`?

**Comment by osvenskan** [comment]
>Observations about one don't generalize to the other.  

Thanks for the info. This is a great summary.

> While a segfault may be the usual and expected result when (accidentally) straying from supported behavior when doing C development, I expect Python to never segfault due to user error (which is why it initially didn't even occur to me to dig deeper before filing this issue). 

Yeah, but this library is just a thin wrapper around a bunch of C functions, so it's absolutely possible to create segfaults and other fun with it. That's true of any Python library written partially or principally in C. My code hasn't been flawless; I've caused a segfault bug or two in this module but not in the last 10 years I don't think.

> Maybe this gotcha is worth a note in the platform notes in USAGE.md?

I'll consider it, but my gut reaction is that I don't want to take on the job of explaining (and maintaining the explanation) of the nuances of the `/dev` filesystem, especially since (a) I don't use Linux and (b) one can use `posix_ipc` and never look at `/dev`.


Thanks for doing lots of legwork yourself and good luck with `posix_ipc`.
